# project_number: 233183858767
application: managedvm-provaric
runtime: python27
api_version: 1
vm: true
threadsafe: yes
# Reflected in ./VERSION
version: 101
#...
manual_scaling:
  instances: 1
vm_settings:
  machine_type: n1-standard-1
  #root_setup_command: /bin/bash {app_name}/setup.sh
